name: Poco
favicon: null
layout_spectrum: 0.1465446196962148
typography_spectrum: 0.6138951925095171
title: Little bits of news
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6820935469586402
  lightness: 0.8761997690889984
  saturation: 0.8134368078317493
  rhythmicContrast: 0.0650593382306397
purpose: []
